import "./globals.css";
import { Inter } from "next/font/google";
import { componentLog, timeString } from "@/app/logger";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { B_TS: buildId = "local_build" } = process.env;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const time = timeString();
  componentLog("RootLayout", `render time ${time}`, buildId);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" min-h-screen flex-col items-center justify-between p-24">
          <p>
            Root Layout. Created: {time}. Build-Id: {buildId}
          </p>
          <div className={"border-amber-700 border-2 p-4"}>{children}</div>
        </main>
      </body>
    </html>
  );
}
