import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><main>{children}</main>
      <div>
        <Link href={"/"}>Home</Link>
      </div>
      </body>
    </html>
  )
}
